// -------------------------------------------------------------------
// Sample Jenkinsfile for reference only – not part of active CI/CD.
// Keep this file in root folder to use.
// -------------------------------------------------------------------
pipeline {
    agent {
        docker { image 'golang:1.24.2' }
    }
    stages {
        stage('First Stage') {
            steps {
                sh 'go version'
            }
        }
    }
}
